# Generated by Django 3.1.2 on 2020-11-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postagem',
        ),
    ]
