# Generated by Django 3.1.2 on 2020-11-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_postagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['data']},
        ),
    ]
