# Generated by Django 3.1.2 on 2020-11-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_auto_20201104_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
