# Generated by Django 3.1.2 on 2020-11-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0010_auto_20201104_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={},
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
