# Generated by Django 3.1.2 on 2020-11-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_auto_20201104_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['data']},
        ),
    ]
