# Generated by Django 3.1.2 on 2020-11-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0012_auto_20201104_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
