# Generated by Django 3.1.2 on 2020-11-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0017_auto_20201104_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
