# Generated by Django 3.1.2 on 2020-11-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0018_auto_20201104_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.TimeField(auto_now=True),
        ),
    ]
